**Name :  Dogodzi Marion Selasi Kwaku**            
**ID   : 11011909**  
**Class: AREN**

In [73]:
pip install matplotlib
pip install pandas
pip install numpy

SyntaxError: invalid syntax (518857359.py, line 1)

In [62]:
import pandas as pd
import matplotlib as mpl
import numpy as np

In [63]:
dataset= pd.read_csv('red_wine.csv')

In [64]:
dataset

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5.0
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5.0
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5.0
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6.0
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...
1594,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5.0
1595,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6.0
1596,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6.0
1597,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5.0
1598,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6.0

In [65]:
dataset.head(10)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5.0
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5.0
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5.0
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6.0
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5.0
5,7.4,0.66,0.00,1.8,0.075,13.0,40.0,0.9978,3.51,0.56,9.4,5.0
6,7.9,0.60,0.06,1.6,NaN,15.0,59.0,0.9964,3.30,0.46,9.4,5.0
7,7.3,0.65,0.00,1.2,0.065,15.0,21.0,0.9946,3.39,0.47,10.0,7.0
8,7.8,0.58,0.02,2.0,0.073,9.0,18.0,0.9968,3.36,0.57,9.5,7.0
9,7.5,0.50,0.36,6.1,0.071,17.0,102.0,0.9978,3.35,0.80,10.5,5.0

In [66]:
dataset.tail(20)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
1579,6.2,0.560,0.09,1.7,0.053,24.0,32.0,0.99402,3.54,0.60,11.3,5.0
1580,7.4,0.350,0.33,2.4,0.068,9.0,26.0,0.99470,3.36,0.60,11.9,6.0
1581,6.2,0.560,0.09,1.7,0.053,24.0,32.0,0.99402,3.54,0.60,11.3,5.0
1582,6.1,0.715,0.10,2.6,0.053,13.0,27.0,0.99362,3.57,0.50,11.9,5.0
1583,6.2,0.460,0.29,2.1,0.074,32.0,98.0,0.99578,3.33,0.62,9.8,5.0
1584,6.7,0.320,0.44,2.4,0.061,24.0,34.0,0.99484,3.29,0.80,11.6,7.0
1585,7.2,0.390,0.44,2.6,0.066,22.0,48.0,0.99494,3.30,0.84,11.5,6.0
1586,7.5,0.310,0.41,2.4,0.065,34.0,60.0,0.99492,3.34,0.85,11.4,6.0
1587,5.8,0.610,0.11,1.8,0.066,18.0,28.0,0.99483,3.55,0.66,10.9,6.0
1588,7.2,0.660,0.33,2.5,0.068,34.0,102.0,0.99414,3.27,0.78,12.8,6.0
1589,6.6,0.725,0.20,7.8,0.073,29.0,79.0,0.99770,3.29,0.54,9.2,5.0
1590,6.3,0.550,0.15,1.8,0.077,26.0,35.0,0.99314,3.32,0.82,11.6,6.0
1591,5.4,0.740,0.09,1.7,0.089,16.0,26.0,0.99402,3.67,0.56,11.6,6.0
1592,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6.0
1593,6.8,0.620,0.08,1.9,0.068,28.0,38.0,0.99651,3.42,0.82,9.5,6.0
1594,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5.0
1595,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6.0
1596,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6.0
1597,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5.0
1598,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6.0

In [67]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fixed acidity         1598 non-null   float64
 1   volatile acidity      1598 non-null   float64
 2   citric acid           1599 non-null   float64
 3   residual sugar        1599 non-null   float64
 4   chlorides             1595 non-null   float64
 5   free sulfur dioxide   1598 non-null   float64
 6   total sulfur dioxide  1599 non-null   float64
 7   density               1598 non-null   float64
 8   pH                    1599 non-null   float64
 9   sulphates             1599 non-null   float64
 10  alcohol               1599 non-null   float64
 11  quality               1598 non-null   float64
dtypes: float64(12)
memory usage: 150.0 KB

In [68]:
dataset.describe()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
count,1598.000000,1598.000000,1599.000000,1599.000000,1595.000000,1598.000000,1599.000000,1598.000000,1599.000000,1599.000000,1599.000000,1598.000000
mean,8.318335,0.527747,0.270976,2.538806,0.087476,15.867334,46.467792,0.996746,3.311113,0.658149,10.422983,5.635795
std,1.740863,0.179092,0.194801,1.409928,0.047117,10.459029,32.895324,0.001887,0.154386,0.169507,1.065668,0.807771
min,4.600000,0.120000,0.000000,0.900000,0.012000,1.000000,6.000000,0.990070,2.740000,0.330000,8.400000,3.000000
25%,7.100000,0.390000,0.090000,1.900000,0.070000,7.000000,22.000000,0.995600,3.210000,0.550000,9.500000,5.000000
50%,7.900000,0.520000,0.260000,2.200000,0.079000,14.000000,38.000000,0.996750,3.310000,0.620000,10.200000,6.000000
75%,9.200000,0.640000,0.420000,2.600000,0.090000,21.000000,62.000000,0.997830,3.400000,0.730000,11.100000,6.000000
max,15.900000,1.580000,1.000000,15.500000,0.611000,72.000000,289.000000,1.003690,4.010000,2.000000,14.900000,8.000000

In [69]:
dataset.isnull().sum()

fixed acidity           1
volatile acidity        1
citric acid             0
residual sugar          0
chlorides               4
free sulfur dioxide     1
total sulfur dioxide    0
density                 1
pH                      0
sulphates               0
alcohol                 0
quality                 1
dtype: int64

In [70]:
dataset.dropna(inplace=True)

In [71]:
dataset.drop_duplicates(inplace=True)

In [72]:
#Histograms for numeric columns
for column in dataset.columns:
    if dataset[column].dtype in ['int64', 'float64']:
        mpl.hist(dataset[column], bins=20, color='blue', alpha=0.7)
        mpl.xlabel('X-axis label')
        mpl.ylabel('Y-axis label')
        mpl.title(f'Histogram of {column}')
        mpl.show()

AttributeError: module 'matplotlib' has no attribute 'hist'

In [ ]:
# Create scatter plots for pairs of numeric columns
numeric_columns = dataset.select_dtypes(include=['int64', 'float64']).columns

for i in range(len(numeric_columns)):
    for j in range(i+1, len(numeric_columns)):
        mpl.scatter(dataset[numeric_columns[i]], dataset[numeric_columns[j]])
        mpl.xlabel(numeric_columns[i])
        mpl.ylabel(numeric_columns[j])
        mpl.title(f'Scatter Plot: {numeric_columns[i]} vs {numeric_columns[j]}')
        mpl.show()

In [ ]:
# Correlation heatmap 
correlation_matrix = dataset.corr()

mpl.figure(figsize=(10, 8))
mpl.imshow(correlation_matrix, cmap='coolwarm', interpolation='none')
mpl.colorbar().set_label('Correlation Coefficient')
mpl.xticks(range(len(correlation_matrix)), correlation_matrix.columns, rotation=90)
mpl.yticks(range(len(correlation_matrix)), correlation_matrix.columns)
mpl.title('Correlation Heatmap')
mpl.show()

In [ ]:
#Box plots for all numeric columns
for column in dataset.select_dtypes(include=['int64', 'float64']).columns:
    mpl.boxplot(df[column])
    mpl.title(f'Box Plot of {column}')
    mpl.show()

##  Histograms of numerical columns 
Histograms visually represent the distribution of each feature. Key observations may include:

- Fixed Acidity:  Appears normally distributed
- Volatile Acidity:  Skewed to the right.
- Citric Acid:  Skewed to the right.
- Residual Sugar:  Skewed to the right.
- Chlorides:  Skewed to the right

These visualisations help to identify potential outliers amd understand the shape of the data destributtion.

## Correlation Heatmap 
The correlation heatmap highlights relationships between different features. Key observations may include:

- pH and Fixed Acidity: Negative Correlation.
- Citric Acid and Volatile Acidity: Negative Correlation.
- Density and Alcohol: Negative correlation.

Understanding these correlation can guide feature selection or further analysis.

## Box plots
Box plots provide insights into the distribution of selected chemical properties across different wine qualities. Key observations may include: 

- Fixed Acidity: No clear trend across wine qualities.
- Volatile Acidity: Higher volatile acidity tends to be associated with higher quality.
- Citric Acid: Higher citric acid tends to be associated with higher quality.
- Residual suger and Chlorides: No clear trend across wine qualities.

## Scatter plots
Scatter plots visualize relationsjips between pairs of numeric columns. Key insights may include:

 - Fixed Acidity vs. Volatile Acidity:
   
The scatter plot shows a weak negative correlation between fixed acidity and volatile acidity.
Wines with higher fixed acidity tend to have lower volatile acidity.
- 
Citric Acid vs. Residuals ugar

The scatter plot indicates a positive correlation between citric acid and residual sugar. Wines with higher citric acid content also tend to have higher residual sugars.:
- Density vs. Alcohol:o
The scatter plot suggest a negative correlation between density and alcohol content. Wines with higher alcohol content tend to have lower density.o
-pH vs. Sulphates:
uThe scatter plot shows a weak positive corrrelation between pH and sulphates. Higher pH values are associated with slightly higher dulphate levels. ationships.





In conclusion, this exploratory analysis of the wine dataset provides valuable insights into its characteristics. Key takeaways include:

Most wines in the dataset have quality ratings of 5 or 6.
The distribution of chemical properties varies, with some showing normal distributions and others exhibiting skewness.
Correlation analysis reveals potential relationships between certain chemical properties.
Box plots highlight how specific properties may vary across different wine qualities.
Further analysis, potentially incorporating more features or advanced techniques, may be warranted to gain a deeper understanding of the dataset.